### PR TITLE
Add a state to manage apt's preferences, with tests

### PR DESCRIPTION
**Pull request by javierbertoli**

### CODE REVIEW

**Comment by gravyboat** [comment]
@javierbertoli this looks good. Could you please do me a favor and [squash these commits?](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History#Squashing-Commits)

**Comment by javierbertoli** [comment]
@gravyboat I understand you can [squash them at merge time](https://help.github.com/articles/about-pull-request-merge-squashing/). If that's not enabled, I understand I'll have to close this PR and submit a new one already squashed, right? (Never squashed AFTER submitting a PR). Let me know if it is so, and I'll do it. Sorry for the inconveniences.

**Comment by babilen** [comment]
You can just squash them and then force push into your branch. The PR will reflect that change.

**Comment by gravyboat** [comment]
@javierbertoli Unfortunately the `squash at merge time` functionality isn't enabled on this repo. They didn't enable it by default on all repos, and only owners can do so, which means I would have to get someone from the Salt team to enable it. Thanks for doing the squash locally, and thanks for helping out @babilen.

**Pull request merged**
