### PR TITLE
docs(readme.rst): add doc for apt_conf state + other minor update

### PR DESCRIPTION
**Pull request by sylvainfaivre**
### PR progress checklist (to be filled in by reviewers)

- [ ] Changes to documentation are appropriate (or tick if not required)
- [ ] Changes to tests are appropriate (or tick if not required)
- [ ] Reviews completed

---

### What type of PR is this?

- [x] `[docs]`     Documentation changes

### Does this PR introduce a `BREAKING CHANGE`?

No.

### Describe the changes you're proposing

add doc for apt_conf state + other minor update

### Documentation checklist

- [x] Updated the `README` (e.g. `Available states`).
- [ ] Updated `pillar.example`.

### Testing checklist

- [ ] Included in Kitchen (i.e. under `state_top`).
- [ ] Covered by new/existing tests (e.g. InSpec, Serverspec, etc.).
- [ ] Updated the relevant test pillar.

### CODE REVIEW

**Comment by daks** [comment]
@sylvainfaivre could you also add to `pillar.example` the directives supported in `apt_conf.sls` like `remove_apt_conf` and `clean_apt_conf_d`?

**Comment by javierbertoli** [comment]
@sylvainfaivre, @daks suggestion would be a nice thing to add in this PR, so all the relevant documentation/examples are added in the same PR.

Also, `commitlint` is failing because it needs the [`scope` text in lowercase](https://github.com/saltstack-formulas/apt-formula/pull/64/checks?check_run_id=716955921#step:4:13). If you can amend the message to be `docs(readme.rst): add doc for apt_conf state + other minor update`, we'll be ready to merge it.

**Comment by sylvainfaivre** [comment]
fixed the commit message and added directives in `pillar.example`, thanks for the help @daks and @javierbertoli

**Comment by javierbertoli** [comment]
Merged. Thanks, @sylvainfaivre !

**Pull request merged**
