### PR TITLE
Add a state to manage repositories, with tests

### PR DESCRIPTION
**Pull request by javierbertoli**
This state let's you manage repositories from the pillar, or set some sane defaults

### CODE REVIEW

**Comment by gravyboat** [comment]
Looks good, thanks!

**Comment by aboe76** [comment]
One fix is needed to make it work in the repositories.sls
this:
```
{{ repo}}:
  pkgrepo.managed:
```
should be:
```
{{ repo }}{{ type }}:
  pkgrepo.managed:
  - name: {{ r_type }} {{ r_arch }} {{ r_url }} {{ r_distro }} {{ r_comps }}
  - file: {{ sources_list_dir }}/{{ repo }}-{{ type }}.list
```

to fix the Conflicting ID with the use of multiple types binary and source in one repo.

**Comment by gravyboat** [comment]
Good catch, thanks @aboe76. @javierbertoli could you please fix this and prep another PR?

**Comment by aboe76** [comment]
@javierbertoli thanks for the quick fix.

**Pull request merged**
